### ISSUE TITLE
vim.lsp.util.parse_snippet() is deprecated

### ISSUE THREAD

**Issue by wwwsensor** [dcampos/nvim-snippy#139]
### Description

'vim.lsp.util.parse_snippet() is deprecated' notification is shown.

### Steps to Reproduce

1. Install my [Neovim dotfiles](https://codeberg.org/profitz/nvim).
2. Make some edits that will trigger a LSP-based completion.

### Expected Result

.

### Actual Result

.

### Additional Context

Run ':h deprecated' in Neovim.

**Comment by dcampos** [comment]
Hi! We don't use and never have used that function here. The notification is being triggered because your version of nvim-cmp is too old (0.0.1). The best way to solve it is to update to nvim-cmp master, as it hasn't released any new version since 0.0.1. This change worked for me:

```lua
local spec = {
	{ 'hrsh7th/nvim-cmp', version = false },
	...
```

![image](https://github.com/user-attachments/assets/d796653c-6e96-4c8b-a193-7c862ac05236)
