### ISSUE TITLE
Commit 656a232b6d03770a887ecef6d3617a3f2efed665 breaks tab stops in certain cases

### ISSUE THREAD

**Issue by yorickpeterse** [dcampos/nvim-snippy#22]
I use a custom completion mechanism written in Lua (see [here](https://gitlab.com/yorickpeterse/dotfiles/-/blob/c68774ed5365c475e3d1f113ac1d553d2a7db4fe/dotfiles/.config/nvim/lua/dotfiles/completion.lua)). This completion mechanism supports inserting snippets using Snippy and LSP snippets. One feature is that if there's a single entry, it's expanded immediately instead of requiring you to confirm it.

Today I noticed this seems to break the tab stops in snippets. For example, I have this snippet:

```
snippet context "Insert a context block"
	context '${1:description}' do
		${0}
	end
```

When I type `context` then trigger `snippy.can_expand()` through an insert mapping, all is fine and the tab stops work properly. However, when I trigger the expansion using my completion mechanism (by pressing Tab in my case), it _does_ expand the snippet, but I can't jump to any placeholders.

Running `git bisect` revealed this started happening with commit 656a232b6d03770a887ecef6d3617a3f2efed665. Commits before that one work just fine.

Annoyingly I haven't been able to narrow this down to something simple. For example, if I do `snippy.expand_snippet(snippy.snippets.ruby.context)` in the completion code, it also doesn't work. Weirdly enough, it does work when I use this mapping:

```
imap <C-t> <cmd>lua require('snippy').expand(vim.inspect(require('snippy').snippets.ruby.context))<cr>
```

**Comment by dcampos** [comment]
> Shouldn't autocmd hooks be set up immediately?

Well, ideally they should, but the cursor placement/jumping is done via `nvim_feedkeys` with the `n` flag set, which isn't applied immediately, so there might be situations in which the autocmd event could be triggered before the the cursor is correctly placed. If the CursorMoved event fires too early, for example, it causes problems, because we track the cursor position to check if the snippet state should be cleared.

I've come up with a workaround for this, until a nicer solution is found. Could you check if my latest commit fixes it for you?

**Comment by YorickPeterse** [comment]
@dcampos the latest commit seems to indeed fix this. Thanks!
