### ISSUE TITLE
How to disable unwanted snippet sources

### ISSUE THREAD

**Issue by lynndylanhurley** [dcampos/nvim-snippy#3]
First of all thank you for this library. I've used most of the available snippet plugins for vim / nvim and this is my favorite.

My only problem is that there are certain snippet sources that interfere with function definitions for several languages. They often pop up when I try to use a closing parens `)` or brace `}`. It's really driving me crazy. The additional typing that I need to do to avoid these unwanted completions pretty much negates the benifit of having the snippets that I actually use.

<img width="689" alt="Screen Shot 2021-09-06 at 11 47 54 AM" src="https://user-images.githubusercontent.com/468037/132246383-5b958157-744a-4447-8e57-37fd1627433c.png">

I used the same snippet source (`honza/vim-snippets`) with UltiSnips and never had this issue in any language.

Here's my config:

``` lua
  use {
    'dcampos/nvim-snippy',
    requires = {
      { 'honza/vim-snippets' },
      { 'dcampos/cmp-snippy' }
    },
  }
```

Any idea where these snippets are coming from and how I can disable them?

**Comment by dcampos** [comment]
Because `cmp-snippy` just returns all available snippets in the current scope ,`nvim-cmp` does all the filtering and matching in this case, so you might want to configure the `keyword_length` for `cmp-snippy` to a higher value (default is 1), so it doesn't match single characters:

```lua
  sources = {
    { 
      name = 'snippy',
      keyword_length = 3,
    },
    ...
  }
```

There might be other `nvim-cmp` options that could help too.


The `c)` snippet is coming from the `honza/vim-snippets` source, and is defined for the `_` (default) scope, so it's available for all languages. Currently there's no way to disable specific scopes, but I'm planning to make it configurable in some way.

**Comment by lynndylanhurley** [comment]
Thanks @dcampos , changing the `keyword_length` to `2` solved the problem for me.
