### ISSUE TITLE
Priority for snippets

### ISSUE THREAD

**Issue by pbogut** [dcampos/nvim-snippy#4]
Is there a way to provide priority for shippets? 

What I'm looking for is some way to override one (or more) snippet with my own while using `honza/vim-snippets`. In `ultisnip` you could set priority in the fist line of snippet file like this:

```some.snippets
priority -50

snippet blah "blah"
...
```

Then snippets in file with lower priority would be expanded in case of name conflict. Is there a way to achieve that in snippy?

**Comment by dcampos** [comment]
@pbogut Thanks for trying out Snippy!

The feature you're looking for isn't currently available, but there is a workaround. If you put your custom snippets in `after/snippets/`, they should override any snippets provided by `honza/vim-snippets` in case of name conflict. That happens because Snippy follows the `runtimepath` order when loading snippets, which means snippets defined in folders coming later in the list will always override those loaded before.

**Comment by dcampos** [comment]
Snippet priority has been added to Snippy. The syntax is the same as in UltiSnips. Snippets with higher priority override those with lower priority (default is 0). Because snippets from `honza/vim-snippets` don't have a priority set, it's necessary to use a priority higher than 0 for your own snippets to override them.
